### PR TITLE
Add git-lfs support

### PR DESCRIPTION
**Pull request by spire-allyjweir**
This PR adds support for git-lfs, allowing for files stored in large file storage to be retrieved when pulling from a git repository. Builds on the work from PR #164.

It includes a source configuration parameter called `disable-git-lfs` which allows this behaviour to be disabled. This has been [cribbed from the implementation found in concourse/git-resource](https://github.com/concourse/git-resource/blob/d99b8e5e824f0c4ee4aa096b2ce83894bcf0d2c3/assets/in#L76) using the [`GIT_LFS_SKIP_SMUDGE` envrionment variable documented here](https://github.com/git-lfs/git-lfs/blob/47cf02f0fc459b870bfbaf13c61514da3ff05459/docs/man/git-lfs-config.5.ronn#other-settings) in the git-lfs man pages.

## Testing

I have tested this manually and found success. However, I have not yet extended the existing test suite to test this new functionality. Go is not a language I am overly familiar with. If someone with more experience could assist I would be greatly appreciative.

### Potential Test Cases

1. Retrieves LFS files successfully on `git pull`
    - This can be verified by checking the file size to identify if pointer or actual file. There has been a command added to git-lfs (`git lfs pointer --check [filename]`) but [this was added in git-lfs 2.7.0](https://github.com/git-lfs/git-lfs/releases/tag/v2.7.0) and the alpine package manager `apk` only provides v2.4.2.
2. Verify that `disable_git_lfs` source configuration works

Any other test cases folks can think of, let's get them added too.

### CODE REVIEW

**Comment by spire-allyjweir** [comment]
Hi there, any chance of this being reviewed and potentially merged?

**Comment by spire-allyjweir** [comment]
Closed due to inactivity from maintainers. For anyone else looking for these fixes, we ended up forking and publishing our own Docker image containing these changes. You could do the same if required.

**Comment by jhosteny** [comment]
@spire-allyjweir would you consider reopening this? A number of PRs have been reviewed and merged this week.

**Comment by spire-allyjweir** [comment]
Yeah would still be keen to get this merged if possible! Still looking for guidance on testing.

**Comment by jhosteny** [comment]
@spire-allyjweir FYI, the version of alpine is now 3.11 on master, which will install `git-lfs/2.9.2`. I may take a shot at an integration test later this week if I get some time.

**Comment by spire-allyjweir** [comment]
Any update on the progress of this?

**Comment by spire-allyjweir** [comment]
Any update on this?

**Comment by jhosteny** [comment]
Hi @spire-allyjweir, I know I said I would take a stab at an integration test for this, but I have not had time (just a note: I am not a maintainer on this library). We have been using this PR cherry picked into our own version of the resource for several months, and it works fine on both non-LFS and LFS-enabled repos. 

I still would like to add a test if that will help move the PR along, but I am out through the end of the month. That being said, this change feels simple enough to me that it doesn't need an explicit test.

**Comment by ArjanSchouten** [comment]
Would be very helpful if this functionality is added! Is there any chance the PR will be merged soon?

**Review by rickardl — APPROVED** [review]
LGTM, I don't see our resource being responsible for checking if GIT LFS, a standalone open source project works.

**Pull request merged**
