### PR TITLE
Add Filter for a specific pull request

### PR DESCRIPTION
**Pull request by roryp2**
We need to be able to only build specific PRs in our pipelines and so need to be able to specify which PR number we want to build version for.

If you provide a `pr` option within the `source` configuration of your resource then only commits for that PR will be returned from the `check` task.

### CODE REVIEW

**Comment by itsdalmo** [comment]
Hi and thanks for the PR @roryp2!

Tying the resource to a specific PR number seems a bit brittle, and I'm wondering if we could find a more generic solution if you explain a bit more about your use case?

**Comment by roryp2** [comment]
Sure, so for each PR that we raise we spin up a new pipeline dynamically for it so that it is isolated and changes to the pipeline can be tested within PRs and then that pipeline is destroyed when the PR is close. So in our case we would not want any other PRs being built within that pipeline.

**Comment by itsdalmo** [comment]
> Sure, so for each PR that we raise we spin up a new pipeline dynamically for it so that it is isolated and changes to the pipeline can be tested within PRs and then that pipeline is destroyed when the PR is close. So in our case we would not want any other PRs being built within that pipeline.

Sounds like perhaps it would make sense to generate the pipeline and use the `git-resource` instead of `github-pr-resource` to track commits to the branch that the PR was opened from? Or do you intend to build off forks as well?

**Comment by roryp2** [comment]
We use the pr resource mainly just for the status checks. Potentially we could just recreate the status checks as a separate resource and use the git-resource for the src itself.

**Comment by Typositoire** [comment]
We're also looking for this, until Spaces are GA this sounds like the best approach to avoid PR not building because of race condition.

**Comment by Typositoire** [comment]
Also there's things you can't do off branches directly. Like commenting etc.

**Comment by Typositoire** [comment]
Small update, I did another patch on top of yours for my needs, dunno how useful it is for others but basically we started hitting this: https://github.com/telia-oss/github-pr-resource/issues/26

So I added a more to track ONLY pr numbers. So the first pipeline creates inputs if `p.number` > `request.Version.PR` and the second pipeline (that tracks a PR) continues to use the committedDate.

**Comment by Typositoire** [comment]
Any hopes to see this merged? I've been running this PR for more than a month without issues if that can comfort @itsdalmo :p

**Comment by itsdalmo** [comment]
Hey, sorry for the long radio silence on this one. Been thinking a bit on the use case, and it seems to me like what you really want is a resource which tracks when a (specific) PR is opened/closed, which is somewhat different problem from what _this_ resource solves. As such I believe the `PR` filter belongs in another resource, perhaps the one discussed in https://github.com/telia-oss/github-pr-resource/issues/71?

Thanks again for the PR!

**Comment by Typositoire** [comment]
Sorry but not really. Until spaces arrive, this is the only way to manage PR on big project without skipping updates. I need this resource to track ONLY updates on 1 specific PR and I create one pipeline per PR. I did create a resource to track PR being opened. But I still need this feature. Can we schedule something to show you what I use it for and maybe make you change your mind? @itsdalmo

**Pull request closed without merging**
