### PR TITLE
Add PR Body to metadata

### PR DESCRIPTION
**Pull request by RNag**
Referenced https://developer.github.com/v4/object/pullrequest/
Referenced https://github.com/telia-oss/github-pr-resource/pull/158 so I could figure out where I need to add the changes (Thanks! I'm still a newbie in Go 😄 )

This can be useful for performing some validations on the contents of the PR body.

### CODE REVIEW

**Comment by RNag** [comment]
Please let me know if you want me to make storing this particular metadata as optional - e.g. it can be as a bool param in the `get` step. I only noticed this might be needed because when I tested it in Concourse CI, I saw the "body" in the resource step UI as showing as a lot of lines (since we have a PR template in our case that tends to be quite lengthy). I wasn't sure if that would be needed or not.

**Comment by RNag** [comment]
Hi @itsdalmo -

Can you please look into the issue why the CI build seems to be failing? I wasn't able to figure it out - from what I saw it looks like all the tests are passing, so I wasn't sure if It was anything I changed 😖

I also double checked that I indented all the lines with tabs this time, if that helps 😅 

Here's the sample log output I saw (wasn't able to figure out what the issue was):
```
go: golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/travis/gopath/pkg/mod/cache/vcs/55179c5d8c4db2eaed9fae4682d4c84a1fd3612df666b372bef3bbb997c9601f: exit status 128:
	fatal: unable to access 'https://go.googlesource.com/sync/': The requested URL returned error: 500
go: golang.org/x/sync@v0.0.0-20190423024810-112230192c58: unknown revision 112230192c58
go: golang.org/x/text@v0.3.2: unknown revision v0.3.2
go: golang.org/x/text@v0.3.0: unknown revision v0.3.0
go: error loading module requirements
task: Failed to run task "ci": task: Failed to run task "build": task: Failed to run task "generate": exit status 1
The command "go get -u -v github.com/go-task/task/cmd/task && task ci" exited with 1.
```

Would appreicate if you could look into this -- Thanks!

**Comment by RNag** [comment]
completely confused as to why the CI build suddenly started passing 😕 

I didn't make any noticeable changes since the last edit. I thought there was a newline missing in the `master` so I tried removing it - then I realized it was actually there so I added it back 😅 

for some reason that alone seemed to fix the CI build though - really not sure how, haha.

**Comment by itsdalmo** [comment]
Hi @RNag and thanks for the PR! Unfortunately I think this could have adverse effects that outweigh the benefits for most people (web view cluttered with the PR body, and also has the potential to put extra strain on Concourse). As such I don't think this feature belongs upstream, but can perhaps be used via your fork? Thanks!

**Pull request closed without merging**
