### PR TITLE
Added submodule clone to git clone over https (no ssh keys required)

### LINKED ISSUE #69: [ Feature Request ] Support for Submodules.
So I've been trying this resource to replace the one from jtarchie but I came across the fact that this doesn't do any submodule init/update. Is it something that other people want? I'm currently working to implement it but having to use HTTPS makes it a bit harder..

### PR DESCRIPTION
**Pull request by djirik**
this commit fixes #69
I've added 
`"git", "config", "--global", "url.https://"+g.AccessToken+":x-oauth-basic@github.com/.insteadOf", "git@github.com:"`
and
`"git", "config", "--global", "url.https://.insteadOf", "git://"`
to git client Init
and 
`git submodule update --init --recursive`
to git pull

### CODE REVIEW

**Comment by itsdalmo** [comment]
Hi and thanks for the PR! The changes look quite different from #119 and I'm not sure why? Could you add some detail here?

**Comment by itsdalmo** [comment]
Closing this due to inactivity. Feel free to reopen if you plan on finishing the PR.

**Comment by djirik** [comment]
Hi, sorry for long answer, I just thought that #119 was never going to finish, and made a fix faster, I've also checked it in our installation and it works just fine

**Comment by elbaro** [comment]
I am using @djirik 's resource and it is working fine. Can we revisit this? @itsdalmo

**Comment by elbaro** [comment]
There is one bug in this PR. When a PR changes the submodule reference, this checks out the old submodule commit.

**Comment by itsdalmo** [comment]
Hi @elbaro - I have to say I'm very hesitant to merge this PR because it changes the behaviour to persist the access token to disk, which helps a few people, but makes the resource less secure for everyone. Unless someone figures out a way to do this without persisting the token I don't think I can merge this in good faith 🤷‍♂

**Pull request closed without merging**
