### PR TITLE
WIP - Clone git submodules on pull

### PR DESCRIPTION
**Pull request by andrewedstrom**
Hey there!

This PR addresses https://github.com/telia-oss/github-pr-resource/issues/69, making it so that git submodules will be pulled when the repo is cloned.

Let me know if you have any questions!

### CODE REVIEW

**Comment by andrewedstrom** [comment]
Still working on this, please don't merge yet

**Comment by djirik** [comment]
Any news on that?

**Comment by djirik** [comment]
I've fixed this and created PR, fyi

**Comment by itsdalmo** [comment]
Closing this PR due to inactivity. Feel free to re-open if you find the time to complete it :)

**Pull request closed without merging**
