### PR TITLE
Rewrite Version Selection, Logging & more

### PR DESCRIPTION
**Pull request by christophermancini**
We are still testing these changes internally and expect further changes as we work out kinks, but creating the PR now so that we can open up dialog about merging these changes upstream.

The bulk of the work in this PR was captured in https://github.com/digitalocean/github-pr-resource/pull/1

### CODE REVIEW

**Comment by christophermancini** [comment]
@itsdalmo I just merged the latest features into our fork, makes this a good time to review my work before more conflicts are introduced.

**Comment by itsdalmo** [comment]
Hi @christophermancini and thank you for the PR! There seems to be a lot of useful features in here, but it's pretty hard to review since it's such a big PR with lots of different features. Are there any particular features in this PR you'd want to see merged in upstream that we could focus on first? 🤔

**Comment by christophermancini** [comment]
@itsdalmo I completely understand that this is a massive PR. My original goal was to refactor the version selection, but then it was rabbit hole after rabbit hole.

My thoughts are, it might be best to merge this to a new branch upstream, maybe an v2-RC? This way, folks in the community can start playing with it and provide feedback, if all looks good, move forward with it in the future. I would be happy to continue to keep it merge-able for the foreseeable future.

We are currently using it internally at DO and making adjustments as we go to get it tuned.

**Comment by christophermancini** [comment]
At this point the resource is working quite well. There are edge cases where if a PR had more than one event in a very short time, the resource produces two versions for that PR when it should have only produced one. That being said, it does not appear to have missed any PRs over the last few weeks averaging 500 builds per day on one of our pipelines that it is implemented on.

**Pull request closed without merging**
