### PR TITLE
Feature request: required_review_approvals parameter

### PR DESCRIPTION
**Pull request by m17ch**
**What**

Implement the `required_review_approvals` parameter, which stops the resource from triggering if the pull request does not have at least `X` approved review(s).

Note: Decided to rename `require_review_approval` parameter to `required_review_approvals`. 

**Why**

My team would like to use this resource to only trigger on pull requests that have been reviewed & explicitly approved by a project maintainer using [GitHub's existing permissions](https://help.github.com/en/articles/about-pull-request-reviews#required-reviews).  The filtering functionality appears to have existed in jtarchie's previous resource - I did my best to replicate.

**Pull Request**
 - [X] Implements a test for this feature
 - [X] Implements the feature
 - [X] Updates the documentation in `README.md`

**Other**

I thought it was worth calling out using GitHub's protected branch rules (see the `Notes` section in README) in tandem with this feature if your objective is very tight control on what gets triggered.  If the branch rules are NOT used, the first approved review will cause all subsequent commits to also trigger the resource.

Please let me know if there are any questions or suggestions and I'll be happy to address.  Thank you!

### CODE REVIEW

**Comment by m17ch** [comment]
For what it's worth, our original objective was nearly identical to the one described in #58 -- we were thinking a PR comment or label to control resource filtering would be the way to go.  However, letting GitHub's existing permission requirements for who can approve a PR simplified things greatly.

**Comment by m17ch** [comment]
@itsdalmo Would you mind reviewing / letting me know if you'd like any changes?

**Comment by itsdalmo** [comment]
Hi @m17ch and thank you for the PR! Sorry for the long wait, I'll try to get this reviewed tomorrow/during the weekend and get back to you 🙌

**Comment by m17ch** [comment]
Thank you for reviewing + feedback, @itsdalmo !

> Since we are collecting the count of approving reviews, perhaps we should allow users to specify how many approving reviews are required (in Github you can require "at least N" reviews) also?

Sure - we could certainly add another config parameter to do that.  My original intention was simply to replicate the behavior in the previous plugin, which appeared to be  "require at least 1 approval." 

Let me know if this aligns with what you were thinking:
  - add another source config parameter `required_approvals` -- document that it should be used in conjunction with `require_review_approval`
  - if `required_approvals` not used/set, default of `1` required approval
  - require sane values for `required_approvals` (i.e.  `1 > X > 100` ) ?


> It would be great if we could add e2e tests. Any suggestions for how that could be done?

This PR was modeled from https://github.com/telia-oss/github-pr-resource/pull/66  which explicitly called out the e2e test.  If you're thinking these should still be added, I may just need to do some investigation & hunt down some examples.

**Comment by itsdalmo** [comment]
I was thinking we could just have a `required_review_approvals: 2`, `required_approving_reviews: 3` or something to that effect, and just specify the number directly instead of adding another variable? Also, we don't need to require sane values I think because it has no bearing on the code - Github just gives us an `int64` back and we can happily compare it to any value the user wants?

**Comment by shinmyung0** [comment]
any news on this? Ive also been waiting for this feature specifically in order to migrate off the legacy pr resource.

**Comment by m17ch** [comment]
Updated parameter name & type from `require_review_approval` (`bool`) to `required_review_approvals` (`int`) and updated documentation to reflect parameter name change.

Built & functionally validated -- think it's ready for another review @itsdalmo .  Let me know if you'd like any other tweaks!

**Comment by shinmyung0** [comment]
Is this resource no longer maintained?

**Comment by itsdalmo** [comment]
> Is this resource no longer maintained?

It is, albeit slower than I would have liked in the summer months :)

This feature will now be built and available under the `dev` tag. Please try it out before I make a release also :)

**Pull request merged**
